### ISSUE TITLE
Cannot perform multiple runs simultaneously from one Jenkins

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-device-farm-jenkins-plugin#39] opened 2016-07-14 22:08 UTC
When I have two Device Farm builds running at the same time on the same Jenkins, the second one to start blocks with the following message:
```
Run Tests on AWS Device Farm is waiting for a checkpoint on <project name and build number>
```
The second job then continues after the first one ends.  I understand that this is a mechanism Jenkins provides to prevent simultaneous access to certain shared resources, but I do not see why this should apply to simultaneous Device Farm runs.  I seem to be able to execute multiple Device Farm runs simultaneously via the AWS web console.

This is significant because it prevents me from running iOS and Android tests simultaneously on the same CI server, or from fragmenting my (large) test suite into several pieces and executing them simultaneously.

**Comment by nikhil-dabhade** [comment] 2016-07-15 01:01
Hi jbelkins,

Can you confirm if you did not have simultaneous runs apart from Jenkins runs ?
For e.g. a run triggered through console in addition to the one triggered through Jenkins ?

What you are describing can be due to some other run filling up your default concurrency of 5 because of which your run from Jenkins will wait until a slot opens up.

**Comment by jbelkins** [comment] 2016-07-15 12:47
Jenkins: v2.13
Device Farm plugin: v1.13

I had no other runs in progress at the time; when I looked in my Device Farm web console, the one run started with Jenkins was the only one in progress.  My Jenkins was trying to simultaneously start two runs with one device each to run in parallel.

I did find that while I had one run in progress initiated with Jenkins, I could perform a second in parallel by uploading my IPA and test suite through the web console, so I don't think the refusal to run in parallel was in Device Farm; it was in Jenkins.

Thanks for your prompt response, BTW.  Let me know if you need any more info.

**Comment by nikhil-dabhade** [comment] 2016-10-13 01:35
Are you still running in this issue? We have been not able to reproduce this issue at our end after thorough testing. 
If it is no longer an issue it would be nice to mark it as closed.

**Comment by jbelkins** [comment] 2016-10-15 04:13
I moved off the project where I was using this plugin, so I can no longer
investigate. You may close.

**Comment by nikhil-dabhade** [comment] 2016-10-15 09:50
Ah. Thanks for the update.
Closing.

**Closed by nikhil-dabhade** 2016-10-15 09:50 UTC
