### ISSUE TITLE
Running a single UI Automator test

### ISSUE THREAD

**Issue by nIvanovp** [awslabs/aws-device-farm-jenkins-plugin#29] opened 2015-11-30 05:30 UTC
To whom it may concern.
I have encountered a problem using aws-device-farm-jenkins-plaugin.
I try to run a single Android UI Automator test via jenkins using aws-device-farm-jenkins-plugin.
I point out in the field 'Filter' of 'com.uiautomator.test.BaseTestRunner#test' but the entire test class (bn.ereader.BaseTestRunner) runs.
Perhaps, you have a solution. 
Thanks.
Best wishes, Nikolai

**Comment by HongdaAWS** [comment] 2015-12-22 22:09
Hi Nikolai,

Sorry that you have issues.
The test filter in Jenkins plugin is only supported for Calabash today.
DeviceFarm will review the feature request and keep you posted with progress.

Thanks,
Hongda

**Comment by anurag1408** [comment] 2016-03-17 23:06
The issue is fixed now (in the latest Device Farm Jenkins build) and you can now specify filter when running Android UI automator test.
I am closing this issue
You can download the latest build from here
https://wiki.jenkins-ci.org/display/JENKINS/AWS+Device+Farm+Plugin

**Closed by anurag1408** 2016-03-17 23:06 UTC
